### ISSUE TITLE
Broken link in readme file

### ISSUE THREAD

**Issue by AswinRaveendran** [Jobin-S/Jobin-S#3]
Hai,
I am writting this to inform you that your readme file has some broken link in the profile section(It shows visits badge). I hope you'll be able to solve that soon enough and make it better. 

Hope that helps :)

**Comment by Jobin-S** [comment]
Thank you Aswin for reporting this issue ❤️.

**Comment by AswinRaveendran** [comment]
Its ok, Thank you for creating one <3

**Comment by AswinRaveendran** [comment]
I think thats it so can I close it. If you say what you want there I'll be happy to help you.
